<a href="https://colab.research.google.com/github/PRihana/Machine-learning/blob/master/24_03_2020(ML)Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We will be using IMDB Movie Data. The data File is "movie_metadata.csv"

In [0]:
import pandas as pd
import numpy as np

In [0]:
# Display the top five rows
df = pd.read_csv('movie_metadata.csv')

In [10]:
df

      color      director_name  ...  aspect_ratio  movie_facebook_likes
0     Color      James Cameron  ...          1.78                 33000
1     Color     Gore Verbinski  ...          2.35                     0
2     Color         Sam Mendes  ...          2.35                 85000
3     Color  Christopher Nolan  ...          2.35                164000
4       NaN        Doug Walker  ...           NaN                     0
...     ...                ...  ...           ...                   ...
5038  Color        Scott Smith  ...           NaN                    84
5039  Color                NaN  ...         16.00                 32000
5040  Color   Benjamin Roberds  ...           NaN                    16
5041  Color        Daniel Hsia  ...          2.35                   660
5042  Color           Jon Gunn  ...          1.85                   456

[5043 rows x 28 columns]

In [12]:
# Display the last three rows
df.tail(3)

      color     director_name  ...  aspect_ratio  movie_facebook_likes
5040  Color  Benjamin Roberds  ...           NaN                    16
5041  Color       Daniel Hsia  ...          2.35                   660
5042  Color          Jon Gunn  ...          1.85                   456

[3 rows x 28 columns]

In [13]:
# Display the top five rows
df.head()

   color      director_name  ...  aspect_ratio  movie_facebook_likes
0  Color      James Cameron  ...          1.78                 33000
1  Color     Gore Verbinski  ...          2.35                     0
2  Color         Sam Mendes  ...          2.35                 85000
3  Color  Christopher Nolan  ...          2.35                164000
4    NaN        Doug Walker  ...           NaN                     0

[5 rows x 28 columns]

In [14]:
# Check the total number of entries you have
print(df.count())
print(df.shape)

color                        5024
director_name                4939
num_critic_for_reviews       4993
duration                     5028
director_facebook_likes      4939
actor_3_facebook_likes       5020
actor_2_name                 5030
actor_1_facebook_likes       5036
gross                        4159
genres                       5043
actor_1_name                 5036
movie_title                  5043
num_voted_users              5043
cast_total_facebook_likes    5043
actor_3_name                 5020
facenumber_in_poster         5030
plot_keywords                4890
movie_imdb_link              5043
num_user_for_reviews         5022
language                     5031
country                      5038
content_rating               4740
budget                       4551
title_year                   4935
actor_2_facebook_likes       5030
imdb_score                   5043
aspect_ratio                 4714
movie_facebook_likes         5043
dtype: int64
(5043, 28)

In [15]:
# Check the No of features
print(df.shape)
print(df.shape[1])

(5043, 28)
28

In [16]:
# Print features Names(Column Names)
print(df.columns)

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [17]:
# Print the row indices of the dataframe
df.index

RangeIndex(start=0, stop=5043, step=1)

In [18]:
# Check the dtype of each and every columns
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [19]:
# Description for Numerical Column min,max,count,25%,50%,75%,std
df.describe()

       num_critic_for_reviews     duration  ...  aspect_ratio  movie_facebook_likes
count             4993.000000  5028.000000  ...   4714.000000           5043.000000
mean               140.194272   107.201074  ...      2.220403           7525.964505
std                121.601675    25.197441  ...      1.385113          19320.445110
min                  1.000000     7.000000  ...      1.180000              0.000000
25%                 50.000000    93.000000  ...      1.850000              0.000000
50%                110.000000   103.000000  ...      2.350000            166.000000
75%                195.000000   118.000000  ...      2.350000           3000.000000
max                813.000000   511.000000  ...     16.000000         349000.000000

[8 rows x 16 columns]

In [20]:
# Description for the categorical Columns count,top,freq
df.describe(include=object)

        color     director_name    actor_2_name  ... language country content_rating
count    5024              4939            5030  ...     5031    5038           4740
unique      2              2398            3032  ...       47      65             18
top     Color  Steven Spielberg  Morgan Freeman  ...  English     USA              R
freq     4815                26              20  ...     4704    3807           2118

[4 rows x 12 columns]

In [21]:
# Missing value count column wise
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [22]:
# Total Missing values count in the DataFrame
df.isnull().sum().sum()

2698

In [23]:
# How many are color movies are there
print(df.color.value_counts())
#(df.color=='Color',df.color=='Black and White')

Color               4815
 Black and White     209
Name: color, dtype: int64

In [24]:
# How many black and white movies are there
df.color.value_counts()

Color               4815
 Black and White     209
Name: color, dtype: int64

In [26]:
# Calculate how many unique movies are there
df['movie_title'].nunique()

4917

In [27]:
# Check whether unique movies count and no of enties in the data are equal or not
df['movie_title'].nunique()==df.movie_title.count()

False

In [28]:
# Director with max movies
df.director_name.value_counts()

Steven Spielberg     26
Woody Allen          22
Martin Scorsese      20
Clint Eastwood       20
Ridley Scott         17
                     ..
Hugh Johnson          1
Nae Caranfil          1
Frank Perry           1
Finn Taylor           1
Anthony Hemingway     1
Name: director_name, Length: 2398, dtype: int64

In [29]:
# How many movies are there with IMBD Score greater than 8
df.movies=df.imdb_score>8
df.movies.value_counts()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

False    4790
True      253
Name: imdb_score, dtype: int64

In [30]:
# Craete a copy of the  dataframe 
data=df.copy()
data

      color      director_name  ...  aspect_ratio  movie_facebook_likes
0     Color      James Cameron  ...          1.78                 33000
1     Color     Gore Verbinski  ...          2.35                     0
2     Color         Sam Mendes  ...          2.35                 85000
3     Color  Christopher Nolan  ...          2.35                164000
4       NaN        Doug Walker  ...           NaN                     0
...     ...                ...  ...           ...                   ...
5038  Color        Scott Smith  ...           NaN                    84
5039  Color                NaN  ...         16.00                 32000
5040  Color   Benjamin Roberds  ...           NaN                    16
5041  Color        Daniel Hsia  ...          2.35                   660
5042  Color           Jon Gunn  ...          1.85                   456

[5043 rows x 28 columns]

In [31]:
# replace the misising values in numerical columns with mean in the copied dataframe
data=df.select_dtypes(exclude=object)
data.shape
data.isna().sum()

num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_1_facebook_likes         7
gross                        884
num_voted_users                0
cast_total_facebook_likes      0
facenumber_in_poster          13
num_user_for_reviews          21
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [32]:
data.fillna(data.mean(),inplace=True)
data.isnull().sum()

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_1_facebook_likes       0
gross                        0
num_voted_users              0
cast_total_facebook_likes    0
facenumber_in_poster         0
num_user_for_reviews         0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64

In [33]:
# Categorical column with most ferquently occured value in that column in the copied dataframe
data=data.select_dtypes(include=['object'])
print(df.shape)
data.isnull().sum()

(5043, 28)

Series([], dtype: float64)

In [34]:
# Check the output for the info function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB